name: Update richlist data
on: push

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm install
      - name: Run app.js
        run: npm start    
      - name: Commit the new data file
        run: |-
          git diff
          git config --global user.email "contact.atmoner@gmail.com"
          git config --global user.name "atmoner"
          git diff --quiet || (git add data/* && git commit -m "Update data richlist")
          git push origin main
